/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tinyp2p;

import java.awt.Color;
import java.awt.Desktop;
import java.awt.Rectangle;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author (._.)
 */
public class Help extends javax.swing.JFrame {

    /**
     * Creates new form Help
     */

    public Help() {
         initComponents();
    }
    
    public Help(Rectangle bounds, String[] ips) {
        initComponents();

//        jScrollPane2.setOpaque(false);
//        jScrollPane2.getViewport().setOpaque(false);
//        jScrollPane2.setBorder(null);
//        jScrollPane2.setViewportBorder(null);
//        
//        jScrollPane3.setOpaque(false);
//        jScrollPane3.getViewport().setOpaque(false);
//        jScrollPane3.setBorder(null);
//        jScrollPane3.setViewportBorder(null);
//        
//        jScrollPane4.setOpaque(false);
//        jScrollPane4.getViewport().setOpaque(false);
//        jScrollPane4.setBorder(null);
//        jScrollPane4.setViewportBorder(null);
//        
//        jTextPane1.setBorder(null);
//        jTextPane1.setBackground(new Color(0, 0, 0, 0));
//      
//        jTextPane2.setBorder(null);
//        jTextPane2.setBackground(new Color(0, 0, 0, 0));
//        
//        jTextPane3.setBorder(null);
//        jTextPane3.setBackground(new Color(0, 0, 0, 0));
//       
        this.setBounds(bounds);
        this.setSize(500,500);
        eip.setText(ips[0]);      
        emne.setText(Mnemonics.getMnemonics(ips[0]));
        iip.setText(ips[1]);
        imne.setText(Mnemonics.getMnemonics(ips[1]));
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        emne = new javax.swing.JTextField();
        imne = new javax.swing.JTextField();
        iip = new javax.swing.JLabel();
        eip = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 452));
        setMinimumSize(new java.awt.Dimension(500, 452));
        setPreferredSize(new java.awt.Dimension(500, 452));
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Your Internal Mnemonic:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 160, -1));

        jButton2.setBackground(new java.awt.Color(255, 224, 193));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jButton2.setText("CLICK HERE");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, -1, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Your External Mnemonic:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 160, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel6.setText("and troubleshooting");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 210, 50));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel10.setText("connecting to peers on your home or office network, ");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 540, 60));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel9.setText(" help with connecting and  sharing,");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 320, 50));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel8.setText("For more info about Mnemonics, ");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 320, 50));

        jLabel7.setFont(new java.awt.Font("Aharoni", 1, 24)); // NOI18N
        jLabel7.setText("TinyP2P Help");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, 29));

        jButton1.setBackground(new java.awt.Color(255, 224, 193));
        jButton1.setText("Close");
        jButton1.setMargin(new java.awt.Insets(1, 10, 1, 10));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, -1, -1));

        emne.setEditable(false);
        emne.setFont(new java.awt.Font("Courier New", 0, 10)); // NOI18N
        emne.setText("jTextField2");
        emne.setPreferredSize(new java.awt.Dimension(59, 23));
        getContentPane().add(emne, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 130, -1));

        imne.setEditable(false);
        imne.setFont(new java.awt.Font("Courier New", 0, 10)); // NOI18N
        imne.setText("jTextField4");
        imne.setPreferredSize(new java.awt.Dimension(59, 23));
        getContentPane().add(imne, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 130, -1));

        iip.setFont(new java.awt.Font("Courier New", 0, 10)); // NOI18N
        iip.setText("jLabel6");
        getContentPane().add(iip, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 100, -1));

        eip.setFont(new java.awt.Font("Courier New", 0, 10)); // NOI18N
        eip.setText("jLabel8");
        getContentPane().add(eip, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 110, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tiny5.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg2.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        try{
        help();
       }catch(IOException x){}
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
         try{
        help();
       }catch(IOException x){}
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
       try{
        help();
       }catch(IOException x){}
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
         try{
        help();
       }catch(IOException x){}
    }//GEN-LAST:event_jLabel10MouseClicked
    private void help() throws IOException{
        Desktop.getDesktop().open(new File("USERMANUAL.html"));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            
                new Help().setVisible(true); 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel eip;
    private javax.swing.JTextField emne;
    private javax.swing.JLabel iip;
    private javax.swing.JTextField imne;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
