/*
* The MIT License
*
* Copyright 2015 Nicky.
*
* Permission is hereby granted, free of charge, to any person obtaining a copy
* of this software and associated documentation files (the "Software"), to deal
* in the Software without restriction, including without limitation the rights
* to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
* copies of the Software, and to permit persons to whom the Software is
* furnished to do so, subject to the following conditions:
*
* The above copyright notice and this permission notice shall be included in
* all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
* THE SOFTWARE.
*/
package tinyp2p;

import java.awt.Rectangle;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.Arrays;
import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.hive2hive.core.api.configs.NetworkConfiguration;

/**
 *
 * @author Nicky
 */
public class JoinNet extends javax.swing.JFrame {
    public String ip;
    setupConnection sc = new setupConnection();
    ConnectInfo ci;
    String[] ips;
    /**
     * Creates new form JoinNet
     * @param bounds
     * @param ips
     */
    public JoinNet(Rectangle bounds, String[] ips) {      
        this.ips = ips;
        initComponents();  
        this.setBounds(bounds);
        tinyButt.setOpaque(false);
        tinyButt.setContentAreaFilled(false); //to make the content area transparent
        tinyButt.setBorderPainted(false);
      
    }
    
     public JoinNet() {      
        initComponents();
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tinyButt = new javax.swing.JButton();
        help = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Aharoni", 1, 24)); // NOI18N
        jLabel1.setText("TinyP2P");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, 29));

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 159, 25));

        jLabel3.setText("Enter the IP address or TinyP2P mnemonic of anyone ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 300, -1));

        jLabel4.setText("currently connected to the TinyNet you wish to join");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 280, -1));

        jButton1.setBackground(new java.awt.Color(255, 224, 193));
        jButton1.setText("Join");
        jButton1.setMargin(new java.awt.Insets(1, 10, 1, 10));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, -1, -1));

        jLabel6.setFont(new java.awt.Font("Aharoni", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 0));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 330, 20));

        tinyButt.setBackground(new java.awt.Color(204, 255, 204));
        tinyButt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tiny7.png"))); // NOI18N
        tinyButt.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tinyButt.setMargin(new java.awt.Insets(0, 0, 0, 0));
        tinyButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tinyButtActionPerformed(evt);
            }
        });
        getContentPane().add(tinyButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 40, 40));

        help.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        help.setForeground(new java.awt.Color(0, 51, 204));
        help.setText(" ? ");
        help.setToolTipText("A TinyP2P mnemonic is an easy way to remember your IP");
        help.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51)));
        getContentPane().add(help, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg1.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -2, 500, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
        
    
    private String createNodeID() {
        return UUID.randomUUID().toString();
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String nodeID = createNodeID();
            String inet = jTextField1.getText();        
            
          
            if (inet.equalsIgnoreCase("localhost") || inet.equalsIgnoreCase("")){
                inet = "127.0.0.1";
            }
           
            if(validMne(inet)){
                inet = Mnemonics.getIP(inet);
             
            }
            ip = inet;
            if(ConnectMenu.validIP(inet)){
                InetAddress bootstrapAddress = InetAddress.getByName(inet);
                sc.buildNode();             
                NetworkConfiguration config = NetworkConfiguration.create(nodeID, bootstrapAddress);
                boolean success = sc.connectNode(config);
                //ips[1] = sc.node.getPeer().peerAddress().peerSocketAddress().toString().substring(2).split(",")[0];
                ips[1] = ConnectMenu.getInternalIP(sc.node);
                ips[0] = ConnectMenu.getExternalIP();
               if (success){
                  System.out.println(Arrays.toString(ips));
                ci = new ConnectInfo(sc.node, ips, this.getBounds());
                ci.setVisible(true);
                this.dispose();
               }

            }
            else{
                jLabel6.setText("Please enter a valid IP Address or TinyP2P Mnemonic");
            }
        } catch (UnknownHostException e) {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
//            ConnectInternal cint = new ConnectInternal(sc.node, ip);
//            cint.setVisible(true);
            //this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(JoinNet.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tinyButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tinyButtActionPerformed
        Help h = new Help(this.getBounds(),ips);
        h.setVisible(true);
    }//GEN-LAST:event_tinyButtActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            jButton1.doClick();
        }       
    }//GEN-LAST:event_jTextField1KeyPressed

    public boolean validMne(String ip){
       if (ip == null || ip.isEmpty()) {
                return false;
            }
       
        String[] parts = ip.split( " " );
            if ( parts.length != 4 ) {
                return false;
            }
            
        for ( String s : parts ) {
                if ( (s.length() != 3) ) {
                    return false;
                }
            }
        return !ip.endsWith(".");
    }
        
    
//    public static boolean validIP (String ip) {
//    try {
//        if (ip == null || ip.isEmpty()) {
//            return false;
//        }
//
//        String[] parts = ip.split( "\\." );
//        if ( parts.length != 4 ) {
//            return false;
//        }
//
//        for ( String s : parts ) {
//            int i = Integer.parseInt( s );
//            if ( (i < 0) || (i > 255) ) {
//                return false;
//            }
//        }
//        if(ip.endsWith(".")) {
//                return false;
//        }
//
//        return true;
//    } catch (NumberFormatException nfe) {
//        return false;
//    }
//    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JoinNet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JoinNet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JoinNet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JoinNet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
//</editor-fold>
//</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JoinNet().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel help;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton tinyButt;
    // End of variables declaration//GEN-END:variables
}
