/*
* The MIT License
*
* Copyright 2015 Nicky.
*
* Permission is hereby granted, free of charge, to any person obtaining a copy
* of this software and associated documentation files (the "Software"), to deal
* in the Software without restriction, including without limitation the rights
* to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
* copies of the Software, and to permit persons to whom the Software is
* furnished to do so, subject to the following conditions:
*
* The above copyright notice and this permission notice shall be included in
* all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
* THE SOFTWARE.
*/
package tinyp2p;

import java.awt.Rectangle;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStreamWriter;
import java.net.ServerSocket;
import java.net.Socket;
import java.net.UnknownHostException;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
// java.util.Timer;
import javax.swing.DefaultListModel;
import javax.swing.Timer;
import javax.swing.SwingWorker;
import net.tomp2p.dht.FutureGet;
import net.tomp2p.dht.FuturePut;
import net.tomp2p.dht.PutBuilder;
import net.tomp2p.peers.Number160;
import net.tomp2p.peers.PeerAddress;
import net.tomp2p.peers.PeerStatistic;
import net.tomp2p.storage.Data;
import util.ConsoleFileAgent;
import org.hive2hive.core.api.interfaces.IH2HNode;
import org.hive2hive.core.api.interfaces.IUserManager;
import org.hive2hive.core.exceptions.NoPeerConnectionException;
import org.hive2hive.core.security.UserCredentials;
import org.hive2hive.processframework.exceptions.InvalidProcessStateException;
import org.hive2hive.processframework.exceptions.ProcessExecutionException;

/**
 *
 * @author Nicky
 */

public class MainMenu extends javax.swing.JFrame {
    private String username;
    private String password;
    private IH2HNode node;
    private UserCredentials userCredentials;
    private String[] ips;
   // private DefaultListModel lm = new DefaultListModel();
    
    
    
    public MainMenu() {
        initComponents();
    }
    
    public MainMenu(String User, String pw, IH2HNode node, Rectangle bounds, String[] ips) {
        this.username = User;
        this.password = pw;
        this.node = node;
        this.ips = ips;
        //online.setModel(lm);
        initComponents();
        this.setBounds(bounds);
        tinyButt.setOpaque(false);
        tinyButt.setContentAreaFilled(false); //to make the content area transparent
        tinyButt.setBorderPainted(false);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
//    public void login(){
//        userCredentials = new UserCredentials(username, password, "12345");
//        try{
//            File d;
//            if( registered(userCredentials)){
//                // d = chooseDir();
//                File f = new File ("C:\\");
//                ConsoleFileAgent fileAgent = new ConsoleFileAgent(f);
//                node.getUserManager().createLoginProcess(userCredentials, fileAgent).execute();
//            }
//            else{
//                //d = chooseDir();
//                File f = new File ("C:\\");
//                node.getUserManager().createRegisterProcess(userCredentials).execute();
//                ConsoleFileAgent fileAgent = new ConsoleFileAgent(f);
//                node.getUserManager().createLoginProcess(userCredentials, fileAgent).execute();
//            }
//        }catch(NoPeerConnectionException | InvalidProcessStateException | ProcessExecutionException | InterruptedException e ){System.out.println(e);};
//        
//        PutBuilder f  = new PutBuilder(node.getPeer(),node.getPeer().peerID());
//        try{
//            Data d = new Data(username);
//            f.data(d);
//            FuturePut futurePut = node.getPeer().put(node.getPeer().peer().peerID()).data(new Data(username)).start();
//            futurePut.awaitUninterruptibly();
//        }catch(IOException e){System.out.println(e);}
//    }
//    
    
    //returns whether or not a person is registered or not
    private boolean registered(UserCredentials userCredentials) throws NoPeerConnectionException, InvalidProcessStateException, InterruptedException {
        //System.out.println(node.getPeer().peerAddress());
        IUserManager userManager = node.getUserManager();
        return userManager.isRegistered(userCredentials.getUserId());
    }
//    
    public  void getUsers() {
        DefaultListModel lm = new DefaultListModel();
        online.setModel(lm);
        List<Map<Number160, PeerStatistic>> peerMapVerified = node.getPeer().peerBean().peerMap().peerMapVerified();
        for (Map<Number160, PeerStatistic>  m: peerMapVerified){
            
            for (Map.Entry<Number160, PeerStatistic> entry : m.entrySet())
            {
                PeerStatistic ps = entry.getValue();
                
                FutureGet futureGet = node.getPeer().get(ps.peerAddress().peerId()).start();
                
                futureGet.awaitUninterruptibly();
                
              
                try {
                    lm.addElement(futureGet.data().object());
                    online.setModel(lm);
//
                } catch (ClassNotFoundException | IOException ex) {
                    
                }
                
            }
        }
       // online.updateUI();
    }
    
    int debug = 0;
    
    class displayUsers implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent evt){
            debug++;     
            //System.out.println(valueOf(debug));
            DefaultListModel lm = new DefaultListModel();
            online.setModel(lm);
     
            try{
             List<PeerAddress> peerMap = node.getPeer().peerBean().peerMap().all();
            
           //  if (!peerMap.isEmpty()){
                 
             for (PeerAddress pa : peerMap){
                   
                    FutureGet futureGet = node.getPeer().get(pa.peerId()).start();
                    
                    futureGet.awaitUninterruptibly();
                    
                    if (!futureGet.isEmpty()){
                        try {                 
                            lm.addElement(futureGet.data().object());
                            online.setModel(lm);
                        } catch (ClassNotFoundException | IOException ex) {
                        }
                    }
                     
                     futureGet.cancel();
             }
            online.setModel(lm);
            // }
            }catch(NullPointerException e){ 
                System.out.println("no peers found");
            }  
        }
    }
    
    
//     Timer timer = new Timer();
//
//     TimerTask refreshUsers = new TimerTask() {
//
//        @Override
//        public void run() {
//
//            jLabel3.setText(String.valueOf(c));
//            c++;
//
//            online.setModel(lm);
//
//           // try {
//                //getUsers();
////            DefaultListModel lm = new DefaultListModel();
////            //online.setModel(lm);
////            List<Map<Number160, PeerStatistic>> peerMapVerified = node.getPeer().peerBean().peerMap().peerMapVerified();
////            for (Map<Number160, PeerStatistic>  m: peerMapVerified){
////
////                for (Map.Entry<Number160, PeerStatistic> entry : m.entrySet())
////                {
////                    PeerStatistic ps = entry.getValue();
////
////                    FutureGet futureGet = node.getPeer().get(ps.peerAddress().peerId()).start();
////                    futureGet.awaitUninterruptibly();
////                    try {
////                        lm.addElement(futureGet.data().object());
////                        System.out.println(futureGet.data().object());
////                        online.setModel(lm);
//////
////                    } catch (ClassNotFoundException | IOException ex) {
////                        Logger.getLogger(RootMenuGUI.class.getName()).log(Level.SEVERE, null, ex);
////                    }
////
////                }
//                //           }
////            } catch (InterruptedException ex) {
////                Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
////            }
////            } catch (InterruptedException ex) {
////                Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
////            }
//        }
//    };
//
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        online = new javax.swing.JList();
        tinyButt = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 300));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
        jLabel1.setText("Welcome");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 295, -1));

        jLabel2.setText("Online users");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        online.setBackground(new java.awt.Color(222, 255, 204));
        online.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(online);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 110, 200));

        tinyButt.setBackground(new java.awt.Color(204, 255, 204));
        tinyButt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tiny7.png"))); // NOI18N
        tinyButt.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tinyButt.setMargin(new java.awt.Insets(0, 0, 0, 0));
        tinyButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tinyButtActionPerformed(evt);
            }
        });
        getContentPane().add(tinyButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 40, 40));

        jTextField1.setText("jTextField1");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 200, -1));

        jTextField2.setText("jTextField2");
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 200, -1));

        jLabel4.setText("message to send");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, -1));

        jLabel5.setText("User");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, -1));

        jButton1.setText("send");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, -1));

        jButton2.setText("rec");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 60, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg1.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    SwingWorker loginWorker = new SwingWorker<String, Void>() {
        @Override
        public String doInBackground() {
            userCredentials = new UserCredentials(username, password, "12345");
            try{
                File d;
                if( registered(userCredentials)){
                    // d = chooseDir();
                    File f = new File ("C:\\");
                    ConsoleFileAgent fileAgent = new ConsoleFileAgent(f);
                    node.getUserManager().createLoginProcess(userCredentials, fileAgent).execute();
                }
                else{
                    //d = chooseDir();
                    File f = new File ("C:\\");
                    node.getUserManager().createRegisterProcess(userCredentials).execute();
                    ConsoleFileAgent fileAgent = new ConsoleFileAgent(f);
                    node.getUserManager().createLoginProcess(userCredentials, fileAgent).execute();
                }
            }catch(NoPeerConnectionException | InvalidProcessStateException | ProcessExecutionException | InterruptedException e ){System.out.println(e);};
            
            PutBuilder f  = new PutBuilder(node.getPeer(),node.getPeer().peerID());
            try{
                Data d = new Data(username);
                f.data(d);
                FuturePut futurePut = node.getPeer().put(node.getPeer().peer().peerID()).data(new Data(username)).start();
                futurePut.awaitUninterruptibly();
            }catch(IOException e){System.out.println(e);}
            return null;
        }
        
        @Override
        public void done() {
             
        }
    };
    
    
    SwingWorker usersWorker = new SwingWorker<String, Void>() {
        @Override
        public String doInBackground() {
            DefaultListModel lm = new DefaultListModel();
            online.setModel(lm);
            List<Map<Number160, PeerStatistic>> peerMapVerified = node.getPeer().peerBean().peerMap().peerMapVerified();
            for (Map<Number160, PeerStatistic>  m: peerMapVerified){
                
                for (Map.Entry<Number160, PeerStatistic> entry : m.entrySet())
                {
                    PeerStatistic ps = entry.getValue();System.out.println(ps.toString());
                    FutureGet futureGet = node.getPeer().get(ps.peerAddress().peerId()).start();
                    
                    futureGet.awaitUninterruptibly();
                    
                    //timer.scheduleAtFixedRate(refreshUsers, 0, 1000);
                    
                    try {
                        lm.addElement(futureGet.data().object());
                        online.setModel(lm);
//
                    } catch (ClassNotFoundException | IOException ex) {
                        
                    }
                    
                }
            }
            
            return null;
        }
        @Override
         public void done() {
             //online.updateUI();
         }
    };
    
    
    SwingWorker listener = new SwingWorker<String, Void>() {
        @Override
        public String doInBackground() throws IOException {
            ServerSocket serverSocket = new ServerSocket(15123);
            Socket socket = serverSocket.accept();
            
            
            return null;
        }
        @Override
         public void done() {
            
         }
    };
    
    
    
    
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
       
            // login();
            loginWorker.execute();
            jLabel1.setText("Welcome, "+ username+"!");
            // usersWorker.execute();
            
            displayUsers du = new displayUsers();                      //set up timer
            Timer tmr = new javax.swing.Timer(7000, du);
            
            tmr.addActionListener(du);
            tmr.setInitialDelay(0);
            tmr.setRepeats(true);
            tmr.start();
            
            
        try {
            ServerSocket serverSocket = new ServerSocket(15123);
            Socket socket = serverSocket.accept();
        
        } catch (IOException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
 
    }//GEN-LAST:event_formWindowOpened
    
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
            shutdown();
            System.exit(0);
    }//GEN-LAST:event_formWindowClosed

    private void tinyButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tinyButtActionPerformed
        Help h = new Help(this.getBounds(),ips);
       h.setVisible(true);
       
    }//GEN-LAST:event_tinyButtActionPerformed

    public void sendToPort(String ip, String msg) throws IOException {
        Socket socket = null;
        OutputStreamWriter osw;
        //String str = "Hello World";
        try {
            socket = new Socket(ip, 4014);
            osw =new OutputStreamWriter(socket.getOutputStream(), "UTF-8");
            osw.write(msg, 0, msg.length());
             osw.flush();
        } catch (IOException e) {
            System.err.print(e);
        } finally {
            socket.close();
        }

}
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String f = jTextField1.getText();
       String user = jTextField2.getText();
       
        try {
            sendToPort(f,user);
             
        } catch (IOException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
//
//      Socket socket = new Socket("ip address", 4014);
//       //OutputStream outstream = socket .getOutputStream();
//      // PrintWriter out = new PrintWriter(outstream);
//       
//       String toSend = "String to send";
//       
//       out.print(toSend );
//       
//     
       
               
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            int bytesRead;
            Socket socket = new Socket("146.231.133.148",15123);
            InputStream is = socket.getInputStream();
            // bytesRead = is.read(bytearray,0,bytearray.length);
        } catch (IOException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    
    public void shutdown()  {
        if (node != null && node.isConnected()) {
            node.disconnect();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainMenu().setVisible(true);
                
            }
        });
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JList online;
    private javax.swing.JButton tinyButt;
    // End of variables declaration//GEN-END:variables
    
//    DefaultMutableTreeNode addNodes(DefaultMutableTreeNode curTop, File dir) {
//        String curPath = dir.getPath();
//        DefaultMutableTreeNode curDir = new DefaultMutableTreeNode(curPath);
//        if (curTop != null) { // should only be null at root
//            curTop.add(curDir);
//        }
//        Vector ol = new Vector();
//        String[] tmp = dir.list();
//        for (String tmp1 : tmp) {
//            ol.addElement(tmp1);
//        }
//        Collections.sort(ol, String.CASE_INSENSITIVE_ORDER);
//        File f;
//        Vector files = new Vector();
//        // Make two passes, one for Dirs and one for Files. This is #1.
//        for (int i = 0; i < ol.size(); i++) {
//            String thisObject = (String) ol.elementAt(i);
//            String newPath;
//            if (curPath.equals("."))
//                newPath = thisObject;
//            else
//                newPath = curPath + File.separator + thisObject;
//            if ((f = new File(newPath)).isDirectory())
//                addNodes(curDir, f);
//            else
//                files.addElement(thisObject);
//        }
//        // Pass two: for files.
//        for (int fnum = 0; fnum < files.size(); fnum++)
//            curDir.add(new DefaultMutableTreeNode(files.elementAt(fnum)));
//        return curDir;
//    }
}
